/** Curated unicode emoji set with pt-BR keywords, grouped by category. */
export type EmojiCategoryId =
  | "smileys"
  | "people"
  | "nature"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export type EmojiCategory = {
  id: EmojiCategoryId;
  label: string;
  icon: string;
  emojis: [string, string][]; // [char, keywords]
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Rostos e emoções",
    icon: "😀",
    emojis: [
      ["😀", "sorriso feliz alegre"],
      ["😃", "sorriso feliz"],
      ["😄", "riso feliz"],
      ["😁", "sorriso dentes"],
      ["😆", "risada gargalhada"],
      ["😅", "risada suor alivio"],
      ["🤣", "rolando risada haha"],
      ["😂", "chorando de rir haha risada"],
      ["🙂", "leve sorriso"],
      ["🙃", "de cabeca para baixo ironia"],
      ["😉", "piscadela flerte"],
      ["😊", "feliz timido"],
      ["😇", "anjo santo"],
      ["🥰", "amor coracoes apaixonado"],
      ["😍", "apaixonado amor olhos"],
      ["🤩", "estrelas uau"],
      ["😘", "beijo amor"],
      ["😗", "beijo"],
      ["😚", "beijo"],
      ["😙", "beijo"],
      ["😋", "delicia gostoso lingua"],
      ["😛", "lingua"],
      ["😜", "lingua piscada brincadeira"],
      ["🤪", "louco doido"],
      ["😝", "lingua"],
      ["🤑", "dinheiro rico"],
      ["🤗", "abraco"],
      ["🤭", "ops risinho"],
      ["🤫", "silencio segredo"],
      ["🤔", "pensando duvida"],
      ["🤐", "boca fechada"],
      ["🤨", "desconfiado sobrancelha"],
      ["😐", "neutro"],
      ["😑", "sem expressao"],
      ["😶", "sem boca"],
      ["😏", "malicioso"],
      ["😒", "chateado tedio"],
      ["🙄", "revirando olhos"],
      ["😬", "constrangido"],
      ["🤥", "mentira"],
      ["😌", "aliviado calmo"],
      ["😔", "triste pensativo"],
      ["😪", "sono cansado"],
      ["🤤", "babando"],
      ["😴", "dormindo sono"],
      ["😷", "mascara doente"],
      ["🤒", "doente febre"],
      ["🤕", "machucado"],
      ["🤢", "enjoado nojo"],
      ["🤮", "vomito"],
      ["🥵", "calor quente"],
      ["🥶", "frio"],
      ["😵", "tonto"],
      ["🤯", "explodindo mente uau"],
      ["🤠", "caubói"],
      ["🥳", "festa parabens comemorar"],
      ["😎", "oculos legal"],
      ["🤓", "nerd"],
      ["🧐", "monoculo"],
      ["😕", "confuso"],
      ["😟", "preocupado"],
      ["🙁", "triste"],
      ["😮", "surpreso uau"],
      ["😯", "surpreso"],
      ["😲", "chocado"],
      ["😳", "envergonhado"],
      ["🥺", "suplicando fofo pidao"],
      ["😦", "medo"],
      ["😧", "angustia"],
      ["😨", "medo assustado"],
      ["😰", "ansioso"],
      ["😥", "triste alivio"],
      ["😢", "chorando triste"],
      ["😭", "chorando muito triste"],
      ["😱", "grito medo"],
      ["😖", "frustrado"],
      ["😣", "perseverante"],
      ["😞", "decepcionado"],
      ["😓", "suor triste"],
      ["😩", "cansado"],
      ["😫", "exausto"],
      ["🥱", "bocejo sono"],
      ["😤", "bravo raiva"],
      ["😡", "bravo raiva furioso"],
      ["😠", "bravo"],
      ["🤬", "xingando raiva"],
      ["😈", "diabo travesso"],
      ["💀", "caveira morte"],
      ["💩", "coco"],
      ["🤡", "palhaco"],
      ["👻", "fantasma"],
      ["👽", "alien"],
      ["🤖", "robo"],
      ["😺", "gato feliz"],
      ["😻", "gato amor"],
      ["🙀", "gato susto"],
      ["😿", "gato chorando"],
    ],
  },
  {
    id: "people",
    label: "Pessoas",
    icon: "👋",
    emojis: [
      ["👋", "oi tchau aceno"],
      ["🤚", "mao"],
      ["✋", "mao parar"],
      ["🖐️", "mao"],
      ["👌", "ok certo"],
      ["🤌", "dedos italiano"],
      ["✌️", "paz vitoria"],
      ["🤞", "dedos cruzados sorte"],
      ["🤟", "amor te amo"],
      ["🤘", "rock"],
      ["🤙", "me liga"],
      ["👈", "esquerda"],
      ["👉", "direita"],
      ["👆", "cima"],
      ["👇", "baixo"],
      ["👍", "joia curtir positivo like"],
      ["👎", "negativo deslike"],
      ["✊", "punho forca"],
      ["👊", "soco"],
      ["👏", "palmas aplausos parabens"],
      ["🙌", "maos comemorar"],
      ["🤝", "aperto de maos acordo"],
      ["🙏", "obrigado por favor reza"],
      ["💪", "forte musculo"],
      ["🦾", "braco robotico"],
      ["👀", "olhos olhando"],
      ["🧠", "cerebro"],
      ["👶", "bebe"],
      ["🧒", "crianca"],
      ["👦", "menino"],
      ["👧", "menina"],
      ["🧑", "pessoa"],
      ["👨", "homem"],
      ["👩", "mulher"],
      ["🧓", "idoso"],
      ["👮", "policia"],
      ["🕵️", "detetive"],
      ["👨‍⚕️", "medico"],
      ["👩‍🏫", "professora"],
      ["👨‍💻", "programador trabalho"],
      ["👩‍🍳", "cozinheira"],
      ["🤵", "noivo terno"],
      ["👰", "noiva casamento"],
      ["🎅", "papai noel natal"],
      ["🦸", "heroi"],
      ["🧑‍🎤", "cantor"],
      ["💃", "danca dancando"],
      ["🕺", "danca homem"],
      ["👯", "festa dancando"],
      ["🧘", "meditando calma"],
      ["🏃", "correndo"],
      ["🚶", "andando"],
      ["👫", "casal"],
      ["👪", "familia"],
      ["🗣️", "falando"],
      ["👤", "usuario perfil"],
    ],
  },
  {
    id: "nature",
    label: "Animais e natureza",
    icon: "🐶",
    emojis: [
      ["🐶", "cachorro dog"],
      ["🐱", "gato"],
      ["🐭", "rato"],
      ["🐹", "hamster"],
      ["🐰", "coelho"],
      ["🦊", "raposa"],
      ["🐻", "urso"],
      ["🐼", "panda"],
      ["🐨", "coala"],
      ["🐯", "tigre"],
      ["🦁", "leao"],
      ["🐮", "vaca"],
      ["🐷", "porco"],
      ["🐸", "sapo"],
      ["🐵", "macaco"],
      ["🙈", "macaco nao vejo"],
      ["🐔", "galinha"],
      ["🐧", "pinguim"],
      ["🐦", "passaro"],
      ["🦅", "aguia"],
      ["🦆", "pato"],
      ["🦉", "coruja"],
      ["🐺", "lobo"],
      ["🐗", "javali"],
      ["🐴", "cavalo"],
      ["🦄", "unicornio"],
      ["🐝", "abelha"],
      ["🦋", "borboleta"],
      ["🐌", "caracol"],
      ["🐞", "joaninha"],
      ["🐢", "tartaruga"],
      ["🐍", "cobra"],
      ["🐙", "polvo"],
      ["🦐", "camarao"],
      ["🐟", "peixe"],
      ["🐬", "golfinho"],
      ["🐳", "baleia"],
      ["🦈", "tubarao"],
      ["🐊", "crocodilo"],
      ["🐘", "elefante"],
      ["🦒", "girafa"],
      ["🐄", "vaca"],
      ["🌵", "cacto"],
      ["🌲", "arvore pinheiro"],
      ["🌳", "arvore"],
      ["🌴", "palmeira praia"],
      ["🍀", "trevo sorte"],
      ["🍃", "folhas vento"],
      ["🌺", "flor"],
      ["🌻", "girassol"],
      ["🌹", "rosa amor flor"],
      ["🌷", "tulipa flor"],
      ["🌸", "flor cerejeira"],
      ["🌞", "sol"],
      ["🌝", "lua"],
      ["🌙", "lua noite"],
      ["⭐", "estrela"],
      ["🌟", "estrela brilho"],
      ["✨", "brilho magia"],
      ["⚡", "raio energia"],
      ["🔥", "fogo top"],
      ["🌈", "arco iris"],
      ["☁️", "nuvem"],
      ["🌧️", "chuva"],
      ["❄️", "neve frio"],
      ["🌊", "onda mar"],
    ],
  },
  {
    id: "food",
    label: "Comida e bebida",
    icon: "🍔",
    emojis: [
      ["🍏", "maca verde"],
      ["🍎", "maca"],
      ["🍐", "pera"],
      ["🍊", "laranja"],
      ["🍋", "limao"],
      ["🍌", "banana"],
      ["🍉", "melancia"],
      ["🍇", "uva"],
      ["🍓", "morango"],
      ["🥝", "kiwi"],
      ["🍍", "abacaxi"],
      ["🥥", "coco"],
      ["🥑", "abacate"],
      ["🍅", "tomate"],
      ["🥕", "cenoura"],
      ["🌽", "milho"],
      ["🥔", "batata"],
      ["🍞", "pao"],
      ["🥐", "croissant"],
      ["🧀", "queijo"],
      ["🥚", "ovo"],
      ["🍳", "ovo frito cafe"],
      ["🥞", "panqueca"],
      ["🥓", "bacon"],
      ["🍔", "hamburguer lanche"],
      ["🍟", "batata frita"],
      ["🍕", "pizza"],
      ["🌭", "cachorro quente"],
      ["🌮", "taco"],
      ["🌯", "burrito"],
      ["🥗", "salada"],
      ["🍜", "macarrao sopa"],
      ["🍝", "espaguete massa"],
      ["🍣", "sushi"],
      ["🍤", "camarao frito"],
      ["🍚", "arroz"],
      ["🍰", "bolo"],
      ["🎂", "bolo aniversario parabens"],
      ["🧁", "cupcake"],
      ["🍫", "chocolate"],
      ["🍬", "bala doce"],
      ["🍭", "pirulito"],
      ["🍩", "rosquinha donut"],
      ["🍪", "biscoito cookie"],
      ["🍦", "sorvete"],
      ["☕", "cafe"],
      ["🍵", "cha"],
      ["🧃", "suco"],
      ["🥤", "refrigerante"],
      ["🍺", "cerveja"],
      ["🍻", "brinde cerveja"],
      ["🍷", "vinho"],
      ["🥂", "brinde comemorar"],
      ["🍸", "drink"],
      ["🍾", "champanhe festa"],
      ["🥃", "whisky"],
      ["💧", "agua gota"],
    ],
  },
  {
    id: "activity",
    label: "Atividades",
    icon: "⚽",
    emojis: [
      ["⚽", "futebol bola"],
      ["🏀", "basquete"],
      ["🏈", "futebol americano"],
      ["⚾", "beisebol"],
      ["🎾", "tenis"],
      ["🏐", "volei"],
      ["🏉", "rugby"],
      ["🎱", "sinuca"],
      ["🏓", "ping pong"],
      ["🏸", "badminton"],
      ["🥊", "boxe luta"],
      ["🥋", "artes marciais"],
      ["⛳", "golfe"],
      ["🏹", "arco flecha"],
      ["🎣", "pesca"],
      ["🤿", "mergulho"],
      ["🏊", "natacao"],
      ["🏄", "surf"],
      ["🚴", "bicicleta"],
      ["🏋️", "academia treino"],
      ["🤸", "ginastica"],
      ["🤼", "luta"],
      ["🏆", "trofeu vitoria campeao"],
      ["🥇", "primeiro lugar ouro"],
      ["🥈", "prata"],
      ["🥉", "bronze"],
      ["🏅", "medalha"],
      ["🎯", "alvo foco"],
      ["🎲", "dado jogo"],
      ["🎮", "videogame jogo"],
      ["🕹️", "joystick"],
      ["🎰", "cassino"],
      ["🎳", "boliche"],
      ["🎤", "microfone cantar"],
      ["🎧", "fone musica"],
      ["🎼", "musica"],
      ["🎵", "nota musical"],
      ["🎶", "musica"],
      ["🎸", "guitarra"],
      ["🥁", "bateria"],
      ["🎹", "piano"],
      ["🎺", "trompete"],
      ["🎻", "violino"],
      ["🎬", "cinema filme"],
      ["🎨", "arte pintura"],
      ["🎭", "teatro"],
      ["🎪", "circo"],
      ["🎉", "festa parabens comemorar"],
      ["🎊", "confete festa"],
      ["🎈", "balao festa"],
      ["🎁", "presente"],
      ["🎃", "halloween"],
      ["🎄", "natal"],
      ["🧨", "fogos"],
    ],
  },
  {
    id: "travel",
    label: "Viagens e lugares",
    icon: "🚗",
    emojis: [
      ["🚗", "carro"],
      ["🚕", "taxi"],
      ["🚙", "suv carro"],
      ["🚌", "onibus"],
      ["🚎", "trolebus"],
      ["🏎️", "corrida carro"],
      ["🚓", "policia carro"],
      ["🚑", "ambulancia"],
      ["🚒", "bombeiro"],
      ["🚚", "caminhao"],
      ["🚜", "trator"],
      ["🛵", "moto scooter"],
      ["🏍️", "moto"],
      ["🚲", "bicicleta"],
      ["🛴", "patinete"],
      ["🚏", "ponto onibus"],
      ["🚇", "metro"],
      ["🚆", "trem"],
      ["✈️", "aviao viagem"],
      ["🛫", "decolagem"],
      ["🛬", "pouso"],
      ["🚀", "foguete lancamento"],
      ["🛸", "disco voador"],
      ["🚁", "helicoptero"],
      ["⛵", "veleiro"],
      ["🚢", "navio"],
      ["⚓", "ancora"],
      ["🏖️", "praia"],
      ["🏝️", "ilha"],
      ["🏜️", "deserto"],
      ["🌋", "vulcao"],
      ["🏔️", "montanha"],
      ["🏕️", "acampamento"],
      ["🏡", "casa"],
      ["🏠", "casa"],
      ["🏢", "predio escritorio"],
      ["🏥", "hospital"],
      ["🏦", "banco"],
      ["🏫", "escola"],
      ["⛪", "igreja"],
      ["🕌", "mesquita"],
      ["🏛️", "monumento"],
      ["🗽", "estatua liberdade"],
      ["🗼", "torre"],
      ["🎡", "roda gigante"],
      ["🎢", "montanha russa"],
      ["🌁", "cidade neblina"],
      ["🌃", "cidade noite"],
      ["🌆", "por do sol cidade"],
      ["🗺️", "mapa"],
      ["📍", "local pin"],
      ["🧭", "bussola"],
    ],
  },
  {
    id: "objects",
    label: "Objetos",
    icon: "💡",
    emojis: [
      ["⌚", "relogio"],
      ["📱", "celular telefone"],
      ["💻", "notebook computador"],
      ["🖥️", "computador"],
      ["🖨️", "impressora"],
      ["⌨️", "teclado"],
      ["🖱️", "mouse"],
      ["💾", "salvar disquete"],
      ["💿", "cd"],
      ["📷", "camera foto"],
      ["📸", "foto flash"],
      ["🎥", "camera video"],
      ["📺", "tv"],
      ["📻", "radio"],
      ["🔋", "bateria"],
      ["🔌", "tomada"],
      ["💡", "ideia lampada"],
      ["🔦", "lanterna"],
      ["🕯️", "vela"],
      ["📖", "livro"],
      ["📚", "livros estudo"],
      ["📝", "anotacao escrever"],
      ["✏️", "lapis"],
      ["🖊️", "caneta"],
      ["📌", "alfinete"],
      ["📎", "clipe anexo"],
      ["✂️", "tesoura cortar"],
      ["🔑", "chave"],
      ["🔒", "cadeado bloqueado"],
      ["🔓", "desbloqueado"],
      ["🔨", "martelo"],
      ["🛠️", "ferramentas"],
      ["⚙️", "engrenagem configuracao"],
      ["🧲", "ima"],
      ["💊", "remedio"],
      ["💉", "injecao"],
      ["🩺", "estetoscopio"],
      ["🧴", "sabonete"],
      ["🧹", "vassoura limpeza"],
      ["🛒", "carrinho compras"],
      ["💰", "dinheiro saco"],
      ["💵", "dinheiro nota"],
      ["💳", "cartao"],
      ["🧾", "recibo"],
      ["📦", "caixa pacote"],
      ["📬", "correio"],
      ["✉️", "email carta"],
      ["📢", "megafone aviso"],
      ["🔔", "sino notificacao"],
      ["⏰", "alarme despertador"],
      ["⏳", "ampulheta tempo"],
      ["🔍", "lupa pesquisar"],
      ["🎁", "presente"],
      ["🧸", "urso pelucia"],
      ["👑", "coroa rei"],
      ["👗", "vestido"],
      ["👟", "tenis sapato"],
      ["🕶️", "oculos escuros"],
    ],
  },
  {
    id: "symbols",
    label: "Símbolos",
    icon: "🔣",
    emojis: [
      ["❤️", "coracao amor vermelho"],
      ["🧡", "coracao laranja"],
      ["💛", "coracao amarelo"],
      ["💚", "coracao verde"],
      ["💙", "coracao azul"],
      ["💜", "coracao roxo"],
      ["🖤", "coracao preto"],
      ["🤍", "coracao branco"],
      ["💔", "coracao partido"],
      ["❣️", "coracao"],
      ["💕", "coracoes amor"],
      ["💞", "coracoes"],
      ["💓", "coracao batendo"],
      ["💗", "coracao crescendo"],
      ["💖", "coracao brilhante"],
      ["💘", "coracao flecha"],
      ["💝", "coracao presente"],
      ["💯", "cem top perfeito"],
      ["✅", "check certo feito"],
      ["❌", "errado x"],
      ["⭕", "circulo"],
      ["❗", "exclamacao"],
      ["❓", "pergunta duvida"],
      ["⚠️", "aviso atencao"],
      ["🚫", "proibido"],
      ["♻️", "reciclar"],
      ["🔁", "repetir"],
      ["🔀", "aleatorio"],
      ["▶️", "play"],
      ["⏸️", "pausa"],
      ["⏹️", "parar"],
      ["⏭️", "proximo"],
      ["🔊", "som alto"],
      ["🔇", "mudo"],
      ["🔞", "adulto"],
      ["🆗", "ok"],
      ["🆕", "novo"],
      ["🆓", "gratis"],
      ["🔝", "topo"],
      ["#️⃣", "hashtag"],
      ["1️⃣", "um"],
      ["2️⃣", "dois"],
      ["3️⃣", "tres"],
      ["➕", "mais adicionar"],
      ["➖", "menos"],
      ["✖️", "vezes"],
      ["➗", "dividir"],
      ["💲", "dinheiro cifrao"],
      ["©️", "copyright"],
      ["™️", "marca"],
      ["🔴", "vermelho circulo"],
      ["🟢", "verde circulo"],
      ["🔵", "azul circulo"],
      ["⚫", "preto"],
      ["⚪", "branco"],
      ["🟥", "quadrado vermelho"],
      ["🟩", "quadrado verde"],
      ["♠️", "espadas"],
      ["♥️", "copas"],
      ["♦️", "ouros"],
      ["♣️", "paus"],
    ],
  },
  {
    id: "flags",
    label: "Bandeiras",
    icon: "🏳️",
    emojis: [
      ["🏳️", "bandeira branca"],
      ["🏴", "bandeira preta"],
      ["🏁", "bandeira quadriculada corrida"],
      ["🚩", "bandeira triangular"],
      ["🏳️‍🌈", "bandeira arco iris lgbt orgulho"],
      ["🇧🇷", "brasil"],
      ["🇵🇹", "portugal"],
      ["🇺🇸", "estados unidos eua"],
      ["🇬🇧", "reino unido inglaterra"],
      ["🇪🇸", "espanha"],
      ["🇫🇷", "franca"],
      ["🇮🇹", "italia"],
      ["🇩🇪", "alemanha"],
      ["🇯🇵", "japao"],
      ["🇰🇷", "coreia"],
      ["🇨🇳", "china"],
      ["🇮🇳", "india"],
      ["🇦🇷", "argentina"],
      ["🇨🇱", "chile"],
      ["🇺🇾", "uruguai"],
      ["🇵🇾", "paraguai"],
      ["🇨🇴", "colombia"],
      ["🇲🇽", "mexico"],
      ["🇨🇦", "canada"],
      ["🇦🇺", "australia"],
      ["🇿🇦", "africa do sul"],
      ["🇦🇴", "angola"],
      ["🇲🇿", "mocambique"],
      ["🇨🇻", "cabo verde"],
    ],
  },
];

const ALL: { char: string; kw: string; cat: EmojiCategoryId }[] = EMOJI_CATEGORIES.flatMap((c) =>
  c.emojis.map(([char, kw]) => ({ char, kw, cat: c.id })),
);

function norm(s: string) {
  return s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
}

export function searchEmojis(query: string, limit = 90): string[] {
  const q = norm(query);
  if (!q) return [];
  const out: string[] = [];
  for (const e of ALL) {
    if (e.kw.includes(q)) {
      out.push(e.char);
      if (out.length >= limit) break;
    }
  }
  return out;
}
