/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedStoriesNewRouteImport } from './routes/_authenticated/stories.new'
import { Route as AuthenticatedPIdRouteImport } from './routes/_authenticated/p.$id'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoriesNewRoute = AuthenticatedStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPIdRoute = AuthenticatedPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/p/$id': typeof AuthenticatedPIdRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/p/$id': typeof AuthenticatedPIdRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/p/$id': typeof AuthenticatedPIdRoute
  '/_authenticated/stories/new': typeof AuthenticatedStoriesNewRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/explore'
    | '/settings'
    | '/messages/$conversationId'
    | '/p/$id'
    | '/stories/new'
    | '/u/$username'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/create'
    | '/explore'
    | '/settings'
    | '/'
    | '/messages/$conversationId'
    | '/p/$id'
    | '/stories/new'
    | '/u/$username'
    | '/messages'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/create'
    | '/_authenticated/explore'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/p/$id'
    | '/_authenticated/stories/new'
    | '/_authenticated/u/$username'
    | '/_authenticated/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/new': {
      id: '/_authenticated/stories/new'
      path: '/stories/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof AuthenticatedStoriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$id': {
      id: '/_authenticated/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof AuthenticatedPIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedPIdRoute: typeof AuthenticatedPIdRoute
  AuthenticatedStoriesNewRoute: typeof AuthenticatedStoriesNewRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedPIdRoute: AuthenticatedPIdRoute,
  AuthenticatedStoriesNewRoute: AuthenticatedStoriesNewRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
