/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedWatchIndexRouteImport } from './routes/_authenticated/watch.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace.index'
import { Route as AuthenticatedLivesIndexRouteImport } from './routes/_authenticated/lives.index'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated/ai.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedWatchRoomIdRouteImport } from './routes/_authenticated/watch.$roomId'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedStoriesNewRouteImport } from './routes/_authenticated/stories.new'
import { Route as AuthenticatedPIdRouteImport } from './routes/_authenticated/p.$id'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedMarketplaceNewRouteImport } from './routes/_authenticated/marketplace.new'
import { Route as AuthenticatedMarketplaceIdRouteImport } from './routes/_authenticated/marketplace.$id'
import { Route as AuthenticatedLivesNewRouteImport } from './routes/_authenticated/lives.new'
import { Route as AuthenticatedLiveIdRouteImport } from './routes/_authenticated/live.$id'
import { Route as AuthenticatedGamesOnlineRouteImport } from './routes/_authenticated/games.online'
import { Route as AuthenticatedGamesIdRouteImport } from './routes/_authenticated/games.$id'
import { Route as AuthenticatedCreateVideoRouteImport } from './routes/_authenticated/create.video'
import { Route as AuthenticatedChatsNewRouteImport } from './routes/_authenticated/chats.new'
import { Route as AuthenticatedChatsIdRouteImport } from './routes/_authenticated/chats.$id'
import { Route as AuthenticatedAiThreadIdRouteImport } from './routes/_authenticated/ai.$threadId'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin.withdrawals'
import { Route as AuthenticatedAccountBlockedRouteImport } from './routes/_authenticated/account.blocked'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedUUsernameFollowsRouteImport } from './routes/_authenticated/u.$username.follows'
import { Route as AuthenticatedGamesOnlineRoomRouteImport } from './routes/_authenticated/games.online.$room'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchIndexRoute = AuthenticatedWatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLivesIndexRoute = AuthenticatedLivesIndexRouteImport.update({
  id: '/lives/',
  path: '/lives/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWatchRoomIdRoute =
  AuthenticatedWatchRoomIdRouteImport.update({
    id: '/watch/$roomId',
    path: '/watch/$roomId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoriesNewRoute = AuthenticatedStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPIdRoute = AuthenticatedPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceNewRoute =
  AuthenticatedMarketplaceNewRouteImport.update({
    id: '/marketplace/new',
    path: '/marketplace/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceIdRoute =
  AuthenticatedMarketplaceIdRouteImport.update({
    id: '/marketplace/$id',
    path: '/marketplace/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLivesNewRoute = AuthenticatedLivesNewRouteImport.update({
  id: '/lives/new',
  path: '/lives/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveIdRoute = AuthenticatedLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesOnlineRoute =
  AuthenticatedGamesOnlineRouteImport.update({
    id: '/games/online',
    path: '/games/online',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGamesIdRoute = AuthenticatedGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateVideoRoute =
  AuthenticatedCreateVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => AuthenticatedCreateRoute,
  } as any)
const AuthenticatedChatsNewRoute = AuthenticatedChatsNewRouteImport.update({
  id: '/chats/new',
  path: '/chats/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIdRoute = AuthenticatedChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiThreadIdRoute = AuthenticatedAiThreadIdRouteImport.update({
  id: '/ai/$threadId',
  path: '/ai/$threadId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/admin/withdrawals',
    path: '/admin/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountBlockedRoute =
  AuthenticatedAccountBlockedRouteImport.update({
    id: '/account/blocked',
    path: '/account/blocked',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUUsernameFollowsRoute =
  AuthenticatedUUsernameFollowsRouteImport.update({
    id: '/follows',
    path: '/follows',
    getParentRoute: () => AuthenticatedUUsernameRoute,
  } as any)
const AuthenticatedGamesOnlineRoomRoute =
  AuthenticatedGamesOnlineRoomRouteImport.update({
    id: '/$room',
    path: '/$room',
    getParentRoute: () => AuthenticatedGamesOnlineRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/create': typeof AuthenticatedCreateRouteWithChildren
  '/explore': typeof AuthenticatedExploreRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pro': typeof AuthenticatedProRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/auth/': typeof AuthIndexRoute
  '/account/blocked': typeof AuthenticatedAccountBlockedRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/ai/$threadId': typeof AuthenticatedAiThreadIdRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/chats/new': typeof AuthenticatedChatsNewRoute
  '/create/video': typeof AuthenticatedCreateVideoRoute
  '/games/$id': typeof AuthenticatedGamesIdRoute
  '/games/online': typeof AuthenticatedGamesOnlineRouteWithChildren
  '/live/$id': typeof AuthenticatedLiveIdRoute
  '/lives/new': typeof AuthenticatedLivesNewRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/p/$id': typeof AuthenticatedPIdRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/watch/$roomId': typeof AuthenticatedWatchRoomIdRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/ai/': typeof AuthenticatedAiIndexRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/lives/': typeof AuthenticatedLivesIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/watch/': typeof AuthenticatedWatchIndexRoute
  '/games/online/$room': typeof AuthenticatedGamesOnlineRoomRoute
  '/u/$username/follows': typeof AuthenticatedUUsernameFollowsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/create': typeof AuthenticatedCreateRouteWithChildren
  '/explore': typeof AuthenticatedExploreRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pro': typeof AuthenticatedProRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/account/blocked': typeof AuthenticatedAccountBlockedRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/ai/$threadId': typeof AuthenticatedAiThreadIdRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/chats/new': typeof AuthenticatedChatsNewRoute
  '/create/video': typeof AuthenticatedCreateVideoRoute
  '/games/$id': typeof AuthenticatedGamesIdRoute
  '/games/online': typeof AuthenticatedGamesOnlineRouteWithChildren
  '/live/$id': typeof AuthenticatedLiveIdRoute
  '/lives/new': typeof AuthenticatedLivesNewRoute
  '/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/p/$id': typeof AuthenticatedPIdRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/watch/$roomId': typeof AuthenticatedWatchRoomIdRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/lives': typeof AuthenticatedLivesIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/watch': typeof AuthenticatedWatchIndexRoute
  '/games/online/$room': typeof AuthenticatedGamesOnlineRoomRoute
  '/u/$username/follows': typeof AuthenticatedUUsernameFollowsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/create': typeof AuthenticatedCreateRouteWithChildren
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pro': typeof AuthenticatedProRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/account/blocked': typeof AuthenticatedAccountBlockedRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/ai/$threadId': typeof AuthenticatedAiThreadIdRoute
  '/_authenticated/chats/$id': typeof AuthenticatedChatsIdRoute
  '/_authenticated/chats/new': typeof AuthenticatedChatsNewRoute
  '/_authenticated/create/video': typeof AuthenticatedCreateVideoRoute
  '/_authenticated/games/$id': typeof AuthenticatedGamesIdRoute
  '/_authenticated/games/online': typeof AuthenticatedGamesOnlineRouteWithChildren
  '/_authenticated/live/$id': typeof AuthenticatedLiveIdRoute
  '/_authenticated/lives/new': typeof AuthenticatedLivesNewRoute
  '/_authenticated/marketplace/$id': typeof AuthenticatedMarketplaceIdRoute
  '/_authenticated/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/p/$id': typeof AuthenticatedPIdRoute
  '/_authenticated/stories/new': typeof AuthenticatedStoriesNewRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/_authenticated/watch/$roomId': typeof AuthenticatedWatchRoomIdRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/lives/': typeof AuthenticatedLivesIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/watch/': typeof AuthenticatedWatchIndexRoute
  '/_authenticated/games/online/$room': typeof AuthenticatedGamesOnlineRoomRoute
  '/_authenticated/u/$username/follows': typeof AuthenticatedUUsernameFollowsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/explore'
    | '/notifications'
    | '/pro'
    | '/reels'
    | '/saved'
    | '/settings'
    | '/wallet'
    | '/auth/callback'
    | '/checkout/return'
    | '/auth/'
    | '/account/blocked'
    | '/admin/withdrawals'
    | '/ai/$threadId'
    | '/chats/$id'
    | '/chats/new'
    | '/create/video'
    | '/games/$id'
    | '/games/online'
    | '/live/$id'
    | '/lives/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/messages/$conversationId'
    | '/p/$id'
    | '/stories/new'
    | '/u/$username'
    | '/watch/$roomId'
    | '/account/'
    | '/ai/'
    | '/games/'
    | '/lives/'
    | '/marketplace/'
    | '/messages/'
    | '/watch/'
    | '/games/online/$room'
    | '/u/$username/follows'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create'
    | '/explore'
    | '/notifications'
    | '/pro'
    | '/reels'
    | '/saved'
    | '/settings'
    | '/wallet'
    | '/auth/callback'
    | '/checkout/return'
    | '/'
    | '/auth'
    | '/account/blocked'
    | '/admin/withdrawals'
    | '/ai/$threadId'
    | '/chats/$id'
    | '/chats/new'
    | '/create/video'
    | '/games/$id'
    | '/games/online'
    | '/live/$id'
    | '/lives/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/messages/$conversationId'
    | '/p/$id'
    | '/stories/new'
    | '/u/$username'
    | '/watch/$roomId'
    | '/account'
    | '/ai'
    | '/games'
    | '/lives'
    | '/marketplace'
    | '/messages'
    | '/watch'
    | '/games/online/$room'
    | '/u/$username/follows'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/create'
    | '/_authenticated/explore'
    | '/_authenticated/notifications'
    | '/_authenticated/pro'
    | '/_authenticated/reels'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/auth/callback'
    | '/checkout/return'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/account/blocked'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/ai/$threadId'
    | '/_authenticated/chats/$id'
    | '/_authenticated/chats/new'
    | '/_authenticated/create/video'
    | '/_authenticated/games/$id'
    | '/_authenticated/games/online'
    | '/_authenticated/live/$id'
    | '/_authenticated/lives/new'
    | '/_authenticated/marketplace/$id'
    | '/_authenticated/marketplace/new'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/p/$id'
    | '/_authenticated/stories/new'
    | '/_authenticated/u/$username'
    | '/_authenticated/watch/$roomId'
    | '/_authenticated/account/'
    | '/_authenticated/ai/'
    | '/_authenticated/games/'
    | '/_authenticated/lives/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/messages/'
    | '/_authenticated/watch/'
    | '/_authenticated/games/online/$room'
    | '/_authenticated/u/$username/follows'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/': {
      id: '/_authenticated/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof AuthenticatedWatchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lives/': {
      id: '/_authenticated/lives/'
      path: '/lives'
      fullPath: '/lives/'
      preLoaderRoute: typeof AuthenticatedLivesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/$roomId': {
      id: '/_authenticated/watch/$roomId'
      path: '/watch/$roomId'
      fullPath: '/watch/$roomId'
      preLoaderRoute: typeof AuthenticatedWatchRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/new': {
      id: '/_authenticated/stories/new'
      path: '/stories/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof AuthenticatedStoriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$id': {
      id: '/_authenticated/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof AuthenticatedPIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/new': {
      id: '/_authenticated/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof AuthenticatedMarketplaceNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/$id': {
      id: '/_authenticated/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof AuthenticatedMarketplaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lives/new': {
      id: '/_authenticated/lives/new'
      path: '/lives/new'
      fullPath: '/lives/new'
      preLoaderRoute: typeof AuthenticatedLivesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live/$id': {
      id: '/_authenticated/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof AuthenticatedLiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/online': {
      id: '/_authenticated/games/online'
      path: '/games/online'
      fullPath: '/games/online'
      preLoaderRoute: typeof AuthenticatedGamesOnlineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/$id': {
      id: '/_authenticated/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AuthenticatedGamesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create/video': {
      id: '/_authenticated/create/video'
      path: '/video'
      fullPath: '/create/video'
      preLoaderRoute: typeof AuthenticatedCreateVideoRouteImport
      parentRoute: typeof AuthenticatedCreateRoute
    }
    '/_authenticated/chats/new': {
      id: '/_authenticated/chats/new'
      path: '/chats/new'
      fullPath: '/chats/new'
      preLoaderRoute: typeof AuthenticatedChatsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/$id': {
      id: '/_authenticated/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/$threadId': {
      id: '/_authenticated/ai/$threadId'
      path: '/ai/$threadId'
      fullPath: '/ai/$threadId'
      preLoaderRoute: typeof AuthenticatedAiThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/blocked': {
      id: '/_authenticated/account/blocked'
      path: '/account/blocked'
      fullPath: '/account/blocked'
      preLoaderRoute: typeof AuthenticatedAccountBlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$username/follows': {
      id: '/_authenticated/u/$username/follows'
      path: '/follows'
      fullPath: '/u/$username/follows'
      preLoaderRoute: typeof AuthenticatedUUsernameFollowsRouteImport
      parentRoute: typeof AuthenticatedUUsernameRoute
    }
    '/_authenticated/games/online/$room': {
      id: '/_authenticated/games/online/$room'
      path: '/$room'
      fullPath: '/games/online/$room'
      preLoaderRoute: typeof AuthenticatedGamesOnlineRoomRouteImport
      parentRoute: typeof AuthenticatedGamesOnlineRoute
    }
  }
}

interface AuthenticatedCreateRouteChildren {
  AuthenticatedCreateVideoRoute: typeof AuthenticatedCreateVideoRoute
}

const AuthenticatedCreateRouteChildren: AuthenticatedCreateRouteChildren = {
  AuthenticatedCreateVideoRoute: AuthenticatedCreateVideoRoute,
}

const AuthenticatedCreateRouteWithChildren =
  AuthenticatedCreateRoute._addFileChildren(AuthenticatedCreateRouteChildren)

interface AuthenticatedGamesOnlineRouteChildren {
  AuthenticatedGamesOnlineRoomRoute: typeof AuthenticatedGamesOnlineRoomRoute
}

const AuthenticatedGamesOnlineRouteChildren: AuthenticatedGamesOnlineRouteChildren =
  {
    AuthenticatedGamesOnlineRoomRoute: AuthenticatedGamesOnlineRoomRoute,
  }

const AuthenticatedGamesOnlineRouteWithChildren =
  AuthenticatedGamesOnlineRoute._addFileChildren(
    AuthenticatedGamesOnlineRouteChildren,
  )

interface AuthenticatedUUsernameRouteChildren {
  AuthenticatedUUsernameFollowsRoute: typeof AuthenticatedUUsernameFollowsRoute
}

const AuthenticatedUUsernameRouteChildren: AuthenticatedUUsernameRouteChildren =
  {
    AuthenticatedUUsernameFollowsRoute: AuthenticatedUUsernameFollowsRoute,
  }

const AuthenticatedUUsernameRouteWithChildren =
  AuthenticatedUUsernameRoute._addFileChildren(
    AuthenticatedUUsernameRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRouteWithChildren
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProRoute: typeof AuthenticatedProRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountBlockedRoute: typeof AuthenticatedAccountBlockedRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAiThreadIdRoute: typeof AuthenticatedAiThreadIdRoute
  AuthenticatedChatsIdRoute: typeof AuthenticatedChatsIdRoute
  AuthenticatedChatsNewRoute: typeof AuthenticatedChatsNewRoute
  AuthenticatedGamesIdRoute: typeof AuthenticatedGamesIdRoute
  AuthenticatedGamesOnlineRoute: typeof AuthenticatedGamesOnlineRouteWithChildren
  AuthenticatedLiveIdRoute: typeof AuthenticatedLiveIdRoute
  AuthenticatedLivesNewRoute: typeof AuthenticatedLivesNewRoute
  AuthenticatedMarketplaceIdRoute: typeof AuthenticatedMarketplaceIdRoute
  AuthenticatedMarketplaceNewRoute: typeof AuthenticatedMarketplaceNewRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedPIdRoute: typeof AuthenticatedPIdRoute
  AuthenticatedStoriesNewRoute: typeof AuthenticatedStoriesNewRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRouteWithChildren
  AuthenticatedWatchRoomIdRoute: typeof AuthenticatedWatchRoomIdRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedLivesIndexRoute: typeof AuthenticatedLivesIndexRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedWatchIndexRoute: typeof AuthenticatedWatchIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRouteWithChildren,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProRoute: AuthenticatedProRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountBlockedRoute: AuthenticatedAccountBlockedRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAiThreadIdRoute: AuthenticatedAiThreadIdRoute,
  AuthenticatedChatsIdRoute: AuthenticatedChatsIdRoute,
  AuthenticatedChatsNewRoute: AuthenticatedChatsNewRoute,
  AuthenticatedGamesIdRoute: AuthenticatedGamesIdRoute,
  AuthenticatedGamesOnlineRoute: AuthenticatedGamesOnlineRouteWithChildren,
  AuthenticatedLiveIdRoute: AuthenticatedLiveIdRoute,
  AuthenticatedLivesNewRoute: AuthenticatedLivesNewRoute,
  AuthenticatedMarketplaceIdRoute: AuthenticatedMarketplaceIdRoute,
  AuthenticatedMarketplaceNewRoute: AuthenticatedMarketplaceNewRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedPIdRoute: AuthenticatedPIdRoute,
  AuthenticatedStoriesNewRoute: AuthenticatedStoriesNewRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRouteWithChildren,
  AuthenticatedWatchRoomIdRoute: AuthenticatedWatchRoomIdRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedLivesIndexRoute: AuthenticatedLivesIndexRoute,
  AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedWatchIndexRoute: AuthenticatedWatchIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
